drop schema if exists `i200677` ;
-- DROP TABLE if exists `tranformed`;
-- DROP TABLE if exists `CUSTOMER`;
-- DROP TABLE if exists `PRODUCTS`;
-- DROP TABLE if exists `location`;
-- DROP TABLE if exists `supplier`;
-- DROP TABLE if exists `time1`;
commit;


CREATE SCHEMA `i200677` ;

CREATE TABLE i200677.tranformed (
  PRODUCT_ID VARCHAR(6) NOT NULL, 
  CUSTOMER_ID VARCHAR(4) NOT NULL, 
  STORE_ID VARCHAR(4) NOT NULL, 
  TIME_ID VARCHAR(8) NOT NULL,
  Quantity Double,
  supplier_id VARCHAR(5), 
  Sales DOUBLE 
);

CREATE TABLE i200677.customer (
  CUSTOMER_ID VARCHAR(4) NOT NULL, 
  CUSTOMER_NAME VARCHAR(30) not null,
  CONSTRAINT `CUSTOMERS_PK` PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE i200677.PRODUCTS(
    PRODUCT_ID VARCHAR(6), 
	PRODUCT_NAME VARCHAR(30) NOT NULL, 
    CONSTRAINT `PRODUCTS_PK` PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE i200677.supplier(
	SUPPLIER_ID VARCHAR(5) NOT NULL, 
	SUPPLIER_NAME VARCHAR(30) NOT NULL,
    CONSTRAINT `SUPPLIER_ID` PRIMARY KEY (SUPPLIER_ID)
);

CREATE TABLE i200677.location(
  STORE_ID VARCHAR(4) NOT NULL, 
  STORE_NAME VARCHAR(20) NOT NULL, 
   CONSTRAINT `STORE_ID` PRIMARY KEY (STORE_ID)
);

CREATE TABLE i200677.time1(
  TIME_ID VARCHAR(8) NOT NULL,
  T_DATE DATE NOT NULL,
  CONSTRAINT `TIME_ID` PRIMARY KEY (TIME_ID)
);

